---
# formally in tq common and tqe extras-common
local_working_dir: "{{ lookup('env', 'HOME') }}/.quickstart"
artcl_collect_dir: "{{ local_working_dir }}/collected_files"
working_dir: "/home/{{ undercloud_user }}"
undercloud_user: stack

artcl_collect: true
artcl_collect_list:
  - /var/lib/heat-config/
  - /var/lib/kolla/config_files
  - /var/lib/mistral/
  - /var/lib/oooq-images/*/*.log
  - /var/lib/oooq-images/*/*.sh
  - /var/lib/pacemaker/cib/cib*
  - /var/lib/pacemaker/pengine/pe-input*
  - /var/log/atop*
  - /var/log/dmesg.txt
  - /var/log/host_info.txt
  - /var/log/journal.txt
  - /var/log/postci.txt
  - /var/log/secure
  - /var/log/bootstrap-subnodes.log
  - /var/log/unbound.log
  - /var/log/{{ ansible_pkg_mgr }}.log
  - /var/log/cloud-init*.log
  - /var/log/aodh/
  - /var/log/audit/
  - /var/log/barbican/
  - /var/log/ceilometer/
  - /var/log/ceph/
  - /var/log/cinder/
  - /var/log/cloudkitty/
  - /var/log/cluster/
  - /var/log/config-data/
  - /var/log/congress/
  - /var/log/containers/
  - /var/log/deployed-server-enable-ssh-admin.log
  - /var/log/deployed-server-os-collect-config.log
  - /var/log/designate/
  - /var/log/dmesg/
  - /var/log/extra/
  - /var/log/ec2api/
  - /var/log/glance/
  - /var/log/gnocchi/
  - /var/log/heat/
  - /var/log/heat-launcher/
  - /var/log/horizon/
  - /var/log/httpd/
  - /var/log/ironic/
  - /var/log/ironic-inspector/
  - /var/log/libvirt/
  - /var/log/keystone/
  - /var/log/manila/
  - /var/log/mariadb/
  - /var/log/mistral/
  - /var/log/monasca/
  - /var/log/murano/
  - /var/log/neutron/
  - /var/log/nova/
  - /var/log/novajoin/
  - /var/log/octavia/
  - /var/log/openvswitch/
  - /var/log/ovn/
  - /var/log/pacemaker/
  - /var/log/panko/
  - /var/log/qdr/
  - /var/log/rabbitmq/
  - /var/log/redis/
  - /var/log/sahara/
  - /var/log/sensu/
  - /var/log/swift/
  - /var/log/tacker/
  - /var/log/tempest/
  - /var/log/trove/
  - /var/log/tripleo-container-image-prepare.log
  - /var/log/vitrage/
  - /var/log/watcher/
  - /var/log/zaqar/
  - /var/tmp/sosreport*
  - /etc/
  - /home/*/undercloud-ansible-*
  - /home/*/.instack/install-undercloud.log
  - /home/*/stackrc
  - /home/*/overcloudrc*
  - /home/*/*.log
  - /home/*/*.json
  - /home/*/*.conf
  - /home/*/*.yml
  - /home/*/*.yaml
  - /home/*/*.sh
  - /home/*/*.rst
  - /home/*/*.pem
  - /home/*/deploy-overcloudrc
  - /home/*/network-environment.yaml
  - /home/*/skip_file
  - /home/*/*.subunit
  - /home/*/tempest/*.xml
  - /home/*/tempest/*.html
  - /home/*/tempest/*.log
  - /home/*/tempest/etc/*.conf
  - /home/*/tempest/*.subunit
  - /home/*/tempest/*.json
  - /home/*/tripleo-heat-installer-templates/
  - /home/*/local_tht/
  - /home/*/gating_repo.tar.gz
  - /home/*/browbeat/
  - /usr/share/openstack-tripleo-heat-templates/
  - /home/*/tripleo-heat-templates/
  - /tmp/tripleoclient*
  # The next 2 items are temporary until config-download is executed
  # from a Mistral workflow (WIP in Queens)
  - /home/*/inventory
  - /home/*/tripleo-config-download/
artcl_exclude_list:
  - /etc/udev/hwdb.bin
  - /etc/puppet/modules
  - /etc/project-config
  - /etc/services
  - /etc/selinux/targeted
  - /etc/pki/ca-trust/extracted
  - /etc/alternatives
  - /var/log/journal

# os specific values loaded from tasks/main.yaml
artcl_collect_pkg_list: []

# In upstream logs the compression is handled
# by the storage servers themselves and this
# can be false.  In other storage servers
# the role must compress files.
artcl_gzip: false

artcl_collect_sosreport: false
artcl_sosreport_options: "--batch"

artcl_logstash_files:
  - /home/*/deployed_server_prepare.txt
  - /home/*/docker_journalctl.log
  - /home/*/failed_deployment_list.log
  - /home/*/hostname.sh.log
  - /home/*/install_built_repo.log
  - /home/*/install_packages.sh.log
  - /home/*/install-undercloud.log
  - /home/*/ironic-python-agent.log
  - /home/*/nova_actions_check.log
  - /home/*/overcloud_create_ssl_cert.log
  - /home/*/overcloud_custom_tht_script.log
  - /home/*/overcloud_delete.log
  - /home/*/overcloud_deploy.log
  - /home/*/overcloud_deploy_post.log
  - /home/*/overcloud_failed_prepare_resources.log
  - /home/*/overcloud-full.log
  - /home/*/overcloud_image_build.log
  - /home/*/overcloud_prep_containers.log
  - /home/*/overcloud_prep_images.log
  - /home/*/overcloud_prep_network.log
  - /home/*/overcloud_validate.log
  - /home/*/standalone_deploy.log
  - /home/*/*upgrade*.log
  - /home/*/*update*.log
  - /home/*/repo_setup.log
  - /home/*/repo_setup.sh.*.log
  - /home/*/undercloud_install.log
  - /home/*/undercloud_reinstall.log
  - /home/*/undercloud_custom_tht_script.log
  - /home/*/upgrade-undercloud-repo.sh.log
  - /home/*/validate-overcloud-ipmi-connection.log
  - /home/*/vxlan_networking.sh.log
  - /home/*/workload_launch.log
  - /home/*/pkg_mgr_mirror_error.log
  - /home/*/pkg_mgr_mirror.log
  - /home/*/tempest.log
  - /var/log/bootstrap-subnodes.log
  - /var/log/tripleo-container-image-prepare.log

collect_log_types:
  - system
  - monitoring
  - network
  - openstack
  - container

odl_extra_log_dir: /var/log/extra/odl
odl_extra_info_log: "{{ odl_extra_log_dir }}/odl_info.log"
